### ISSUE TITLE
WebRTC Checklist

### ISSUE THREAD

**Issue by maxmcd** [maxmcd/rivet#1]
- [ ] Record video and audio to single video file
 - [ ] Better error handling on server side
 - [ ] Error handling and better user interface for browser demo code
 - [ ] Hand off WebRTC stream to `tee` and connect to other pad on the fly
